{% set version = "0.8.0" %}
{% set sha256 = "eccd3fc454ed40a1060d2365e179f89cc348ce131fbd2ee8e280246490c2f7eb" %}

package:
  name: chemfiles-python
  version: {{ version }}

source:
  fn: chemfiles.py-{{ version }}.tar.gz
  url: https://github.com/chemfiles/chemfiles.py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win and py2k]
  number: 0
  script: python setup.py install

requirements:
  build:
    # Build time dependencies
    - cmake
    - scikit-build
    - wheel 0.29.0
    # Run time dependencies
    - python
    - enum34  # [py2k]
    - numpy
    - chemfiles-lib 0.8.*
  run:
    - python
    - enum34  # [py2k]
    - numpy
    - chemfiles-lib 0.8.*

test:
  source_files:
    - tests/
  commands:
    - python -m unittest discover -p "*.py" tests

about:
  home: http://chemfiles.org
  license: BSD-3-Clause
  summary: Python binding to chemfiles, a modern library for chemistry file reading and writing
  doc_url: http://chemfiles.org/chemfiles.py/latest/
  dev_url: https://github.com/chemfiles/chemfiles.py

extra:
  recipe-maintainers:
    - luthaf
