{% set version = "0.10.1" %}
{% set sha256 = "32cee8caa9a626340e3a4b74aa7e50559cf06fae80d052dbb8bd223b47cbee63" %}

package:
  name: chemfiles-python
  version: {{ version }}

source:
  fn: chemfiles.py-{{ version }}.tar.gz
  url: https://github.com/chemfiles/chemfiles.py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [(win and py2k) or (python_impl == 'pypy')]
  number: 2
  script: >
    {{ PYTHON }} setup.py install --generator=Ninja --skip-generator-test

requirements:
  build:
    - cmake
  host:
    - python
    - pip
    - scikit-build
    - wheel
    - enum34  # [py2k]
    - numpy
    - chemfiles-lib >=0.10.1,<0.11
  run:
    - python
    - enum34  # [py2k]
    - numpy
    - chemfiles-lib >=0.10.1,<0.11

test:
  source_files:
    - tests/
    - examples/
  commands:
    - python -m unittest discover -p "*.py" tests

about:
  home: http://chemfiles.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python binding to chemfiles, a modern library for chemistry file reading and writing
  doc_url: http://chemfiles.org/chemfiles.py/latest/
  dev_url: https://github.com/chemfiles/chemfiles.py

extra:
  recipe-maintainers:
    - luthaf
