{% set version = "0.7.1" %}
{% set sha256 = "133ae64110f049fcfd2ef5014e3126f28528f63c8f47a211cc57a936f6efc39e" %}

package:
  name: chemfiles-python
  version: {{ version }}

source:
  fn: chemfiles.py-{{ version }}.tar.gz
  url: https://github.com/chemfiles/chemfiles.py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  script:
      - mkdir build
      - cd build
      - cmake -DCMAKE_INSTALL_PREFIX=$PREFIX ..
      - cmake --build . --config release --target install
      # Run tests
      - ctest

requirements:
  build:
    - python
    - cmake
    - setuptools
    - enum34  # [py2k]
    - numpy
    - chemfiles-lib ==0.7.1
  run:
    - python
    - enum34  # [py2k]
    - numpy
    - chemfiles-lib ==0.7.1

test:
  import:
    - chemfiles

about:
  home: http://chemfiles.github.io
  license: MPL-v2.0
  license_file: LICENCE.txt
  summary: Python binding to chemfiles, a modern library for chemistry file reading and writing
  doc_url: http://chemfiles.github.io/chemfiles.py/latest/
  dev_url: https://github.com/chemfiles/chemfiles.py

extra:
  recipe-maintainers:
    - luthaf
