{% set version = "0.10.4" %}
{% set sha256 = "ad56924c0c24f1ec18b0da2928cb938f9a6e8d3e8678242929a57d096b94d15b" %}

package:
  name: chemfiles-python
  version: {{ version }}

source:
  fn: chemfiles.py-{{ version }}.tar.gz
  url: https://github.com/chemfiles/chemfiles.py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - no-cmake-ninja-pip-packages.patch
    - fix-soname-again.patch
    - generate-external-py.patch

build:
  number: 0
  script: |
    {{ PYTHON }} setup.py install

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - ninja
  host:
    - python
    - setuptools
    - wheel
    - numpy >=1.21
    - chemfiles-lib >=0.10.3,<0.11
  run:
    - python
    - numpy
    - chemfiles-lib >=0.10.3,<0.11

test:
  source_files:
    - tests/
    - examples/
  commands:
    - python -m unittest discover -p "*.py" tests

about:
  home: http://chemfiles.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python binding to chemfiles, a modern library for chemistry file reading and writing
  doc_url: http://chemfiles.org/chemfiles.py/latest/
  dev_url: https://github.com/chemfiles/chemfiles.py

extra:
  recipe-maintainers:
    - luthaf
