travis:
  secure:
    BINSTAR_TOKEN: usmm+eD7CodPoJIcyeYpEI1zmQaLqLDg9FBHmbGC2RLDsPf67YvTOXtUKRTuG/W0vP91OOxfs7a8cvYlvrRJNs05NmwyETHQ0TRS1a1Xm6lmabewnolws3FxhiRcEMBePglt9T1TAGV9SYP5PtA4oK+zZnw1cJsYaiefM4tCupFFeDbbEzUBeqalqpi0esyoC7Qr2u80Od/fNasXeYCb+sBDndKJnOcW3MfgswBTXXaZ0H/4YWkUThjFZSOlHcjJXW+MFPyVfgcTiT5Qz3yvyUai3FWZeuI+2stbrgN6Nk0cZJXEFbXGDBmcOSvVMGtxr2M3ntCYVMeGT4IvOCGhrCa3+9c9jnE0F0nprsrgyym2SHcHybl54rWzWh5Vymn8N0UnIP0licBnUcNOp4XhZg0dMI1M6+SgB8cp1wCp7oNsXRQbib5UyzO33bkMwGOLdBBn7L2nukxZumLXRzvBL3hiuS/bVv17ZHirUzlI71835gij+WykE07zAVZt+hZIv6bzq5BKJJqQMdRs0qdV+w78/qsx+78iLGn8sg6B86mvjqtiApAcbqsXVfWcY/LKlSj7GaDy0jCbar7trEsOAmwWHXpAxVj7+XxnqP8zDY/QCRJ09PL6WmHkkuWHsLNrtCWtzzt77br0u0f9aUumNv9GsFdeFdNSOoahmyiN1bo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
